<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="ver-carro.aspx.cs" Inherits="Capa.Presentacion.ver_carro" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="alert alert-info">
        <h3>Ver carro</h3>
        <p class="text-justify">A continuaci&oacute;n puede ver los productos que ha ido seleccionando para su 
            carro de compras. Puede eliminar un producto del carro o modificar la cantidad final de cada item 
            antes de continuar con el proceso de compra.
        </p>
    </div>
    <div class="col-12 p-3">
        <asp:Panel ID="panelVerCarro" runat="server">
            <asp:GridView ID="gridCarro" Width="100%" runat="server" DataKeyNames="Id" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" OnRowCancelingEdit="gridCarro_RowCancelingEdit" OnRowEditing="gridCarro_RowEditing" OnRowUpdating="gridCarro_RowUpdating" OnRowDataBound="gridCarro_RowDataBound" OnRowDeleting="gridCarro_RowDeleting">
                <AlternatingRowStyle BackColor="White" />
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
                <Columns>
                    <asp:BoundField HeaderText="C&oacute;digo de Producto" DataField="IdProducto" ReadOnly="true"/>
                    <asp:BoundField HeaderText="Descripci&oacute;n" DataField="Descripcion" ReadOnly="true"/>
                    <asp:BoundField HeaderText="Precio" DataField="Precio" ReadOnly="true" ItemStyle-HorizontalAlign="Right" />
                    <asp:BoundField HeaderText="Cantidad" DataField="Cantidad" ReadOnly="false" ItemStyle-HorizontalAlign="Right" />
                    <asp:BoundField HeaderText="Total" ReadOnly="true" ItemStyle-HorizontalAlign="Right" />
                </Columns>
            </asp:GridView>
            <p class="text-center"><asp:Label ID="lbAlerta" runat="server" Text="" ForeColor="Red"></asp:Label></p>
            <div class="row">
              <div class="col-md-10 ml-md-auto text-right font-weight-bold">Total Neto $:</div>
              <div class="col-md-2 ml-md-auto text-right font-weight-bold"><asp:Label ID="lbNeto" runat="server" Text="13000.-"></asp:Label></div>
            </div>
            <div class="row">
              <div class="col-md-10 ml-md-auto text-right font-weight-bold">IVA 19% $:</div>
              <div class="col-md-2 ml-md-auto text-right font-weight-bold"><asp:Label ID="lbIva" runat="server" Text="1290.-"></asp:Label></div>
            </div>
            <div class="row">
              <div class="col-md-10 ml-md-auto text-right font-weight-bold">Total $:</div>
              <div class="col-md-2 ml-md-auto text-right font-weight-bold"><asp:Label ID="lbTotal" runat="server" Text="14290.-"></asp:Label></div>
            </div>
            <p class="text-center">Para continuar con el proceso de compra haga click en el bot&oacute;n Procesar Orden. En caso contrario haga click en Cancelar Orden para vaciar el carro de compras.</p>
            <asp:Button ID="btnProcesar" runat="server" Text="Procesar Orden" CssClass="btn btn-success" OnClick="btnProcesar_Click" />&nbsp;&nbsp;<asp:Button ID="btnCancelar" runat="server" Text="Cancelar Orden" CssClass="btn btn-warning" OnClick="btnCancelar_Click" />
        </asp:Panel>
    </div>
    <asp:Panel ID="panelCarroVacio" runat="server" Visible="false">
        <div class="alert alert-danger">
            <p class="text-center">No hay productos cargados en el carro. Haga click <a href="index-cliente.aspx">aqu&iacute;</a> para ir a la sección de Inicio donde podr&aacute; ver el listado de productos.</p>
        </div>
    </asp:Panel>
    <asp:Label ID="lbCantidadCarro" runat="server" Text="" Visible="true" ForeColor="White"></asp:Label>
</asp:Content>
