//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        public decimal ID { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public Nullable<decimal> USUARIO_ID { get; set; }
        public string PREGUNTA { get; set; }
        public string RESPUESTA { get; set; }
        public Nullable<decimal> PROVEEDOR_ID { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
