//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION
    {
        public decimal ID { get; set; }
        public string EMPRESA { get; set; }
        public string RUT { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public string MONEDA { get; set; }
    }
}
