//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PRECIO
    {
        public decimal ID { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal PRECIO_ANTIGUO { get; set; }
        public decimal PRECIO_NUEVO { get; set; }
    }
}
