//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_COMPRA = new HashSet<DETALLE_COMPRA>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public decimal ID { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public decimal STOCK { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public decimal TIPO_PRODUCTO_ID { get; set; }
    
        public virtual ICollection<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
