//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ACCESO = new HashSet<ACCESO>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public decimal ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string MAIL { get; set; }
        public string CARGO { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string TIPO_CLIENTE { get; set; }
    
        public virtual ICollection<ACCESO> ACCESO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
