//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public decimal ID { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public decimal NUM_DOCUMENTO { get; set; }
        public System.DateTime FECHA_DOCUMENTO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal TOTAL { get; set; }
        public decimal USUARIO_ID { get; set; }
    
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
